// Code generated by protoc-gen-go. DO NOT EDIT.
// source: my.proto

/*
Package my is a generated protocol buffer package.

It is generated from these files:
	my.proto

It has these top-level messages:
	TestString
	TestInt
	TestSInt
	TestFixed32
	Test
*/
package my

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestString struct {
	S string `protobuf:"bytes,2,opt,name=s" json:"s,omitempty"`
}

func (m *TestString) Reset()                    { *m = TestString{} }
func (m *TestString) String() string            { return proto.CompactTextString(m) }
func (*TestString) ProtoMessage()               {}
func (*TestString) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestString) GetS() string {
	if m != nil {
		return m.S
	}
	return ""
}

type TestInt struct {
	S int32 `protobuf:"varint,1,opt,name=s" json:"s,omitempty"`
}

func (m *TestInt) Reset()                    { *m = TestInt{} }
func (m *TestInt) String() string            { return proto.CompactTextString(m) }
func (*TestInt) ProtoMessage()               {}
func (*TestInt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TestInt) GetS() int32 {
	if m != nil {
		return m.S
	}
	return 0
}

type TestSInt struct {
	S int32 `protobuf:"zigzag32,1,opt,name=s" json:"s,omitempty"`
}

func (m *TestSInt) Reset()                    { *m = TestSInt{} }
func (m *TestSInt) String() string            { return proto.CompactTextString(m) }
func (*TestSInt) ProtoMessage()               {}
func (*TestSInt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TestSInt) GetS() int32 {
	if m != nil {
		return m.S
	}
	return 0
}

type TestFixed32 struct {
	S uint32 `protobuf:"fixed32,1,opt,name=s" json:"s,omitempty"`
}

func (m *TestFixed32) Reset()                    { *m = TestFixed32{} }
func (m *TestFixed32) String() string            { return proto.CompactTextString(m) }
func (*TestFixed32) ProtoMessage()               {}
func (*TestFixed32) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TestFixed32) GetS() uint32 {
	if m != nil {
		return m.S
	}
	return 0
}

type Test struct {
	Label         string  `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Type          int32   `protobuf:"varint,2,opt,name=type" json:"type,omitempty"`
	Reps          []int64 `protobuf:"varint,3,rep,packed,name=reps" json:"reps,omitempty"`
	RequiredField string  `protobuf:"bytes,5,opt,name=RequiredField" json:"RequiredField,omitempty"`
}

func (m *Test) Reset()                    { *m = Test{} }
func (m *Test) String() string            { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()               {}
func (*Test) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Test) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Test) GetReps() []int64 {
	if m != nil {
		return m.Reps
	}
	return nil
}

func (m *Test) GetRequiredField() string {
	if m != nil {
		return m.RequiredField
	}
	return ""
}

func init() {
	proto.RegisterType((*TestString)(nil), "my.TestString")
	proto.RegisterType((*TestInt)(nil), "my.TestInt")
	proto.RegisterType((*TestSInt)(nil), "my.TestSInt")
	proto.RegisterType((*TestFixed32)(nil), "my.TestFixed32")
	proto.RegisterType((*Test)(nil), "my.Test")
}

func init() { proto.RegisterFile("my.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0xcf, 0xcd, 0xaa, 0xc2, 0x30,
	0x10, 0x05, 0x60, 0xd2, 0x36, 0xb7, 0xed, 0x5c, 0x5d, 0x18, 0x04, 0x83, 0x6e, 0x4a, 0x71, 0xd1,
	0x95, 0x0b, 0xfb, 0x0e, 0x05, 0xb7, 0xd1, 0x17, 0xb0, 0x74, 0x90, 0x48, 0xff, 0x4c, 0x22, 0xd8,
	0xb7, 0x97, 0x4c, 0x17, 0xd2, 0xdd, 0xc9, 0xf9, 0xc8, 0x0c, 0x03, 0x49, 0x37, 0x9d, 0x46, 0x33,
	0xb8, 0x41, 0x04, 0xdd, 0x94, 0xef, 0x01, 0x6e, 0x68, 0xdd, 0xd5, 0x19, 0xdd, 0x3f, 0xc4, 0x0a,
	0x98, 0x95, 0x41, 0xc6, 0x8a, 0x54, 0x31, 0x9b, 0xef, 0x20, 0xf6, 0x76, 0xe9, 0xdd, 0x0c, 0x2c,
	0x63, 0x05, 0xf7, 0x20, 0x21, 0xa1, 0x4f, 0x0b, 0xd9, 0x78, 0x39, 0xc0, 0xbf, 0x97, 0x4a, 0x7f,
	0xb0, 0x29, 0xcf, 0x3f, 0x8c, 0x3d, 0x3e, 0x21, 0xf2, 0x28, 0xb6, 0xc0, 0xdb, 0x7b, 0x8d, 0x2d,
	0x49, 0xaa, 0xe6, 0x87, 0x10, 0x10, 0xb9, 0x69, 0x44, 0x5a, 0xcf, 0x15, 0x65, 0xdf, 0x19, 0x1c,
	0xad, 0x0c, 0xb3, 0xb0, 0x08, 0x15, 0x65, 0x71, 0x84, 0xb5, 0xc2, 0xd7, 0x5b, 0x1b, 0x6c, 0x2a,
	0x8d, 0x6d, 0x23, 0x39, 0x4d, 0x59, 0x96, 0xf5, 0x1f, 0x9d, 0x58, 0x7e, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x4b, 0x9f, 0x34, 0x55, 0xee, 0x00, 0x00, 0x00,
}
