<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto

namespace My;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>my.TestInt</code>
 */
class TestInt extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>int32 s = 1;</code>
     */
    private $s = 0;

    public function __construct() {
        \GPBMetadata\My::initOnce();
        parent::__construct();
    }

    /**
     * <code>int32 s = 1;</code>
     */
    public function getS()
    {
        return $this->s;
    }

    /**
     * <code>int32 s = 1;</code>
     */
    public function setS($var)
    {
        GPBUtil::checkInt32($var);
        $this->s = $var;
    }

}

