<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto

namespace My;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>my.TestString</code>
 */
class TestString extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string s = 2;</code>
     */
    private $s = '';

    public function __construct() {
        \GPBMetadata\My::initOnce();
        parent::__construct();
    }

    /**
     * <code>string s = 2;</code>
     */
    public function getS()
    {
        return $this->s;
    }

    /**
     * <code>string s = 2;</code>
     */
    public function setS($var)
    {
        GPBUtil::checkString($var, True);
        $this->s = $var;
    }

}

