<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace GPBMetadata;

class Helloworld
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89030a1068656c6c6f776f726c642e70726f746f120a68656c6c6f776f" .
            "726c64221c0a0c48656c6c6f52657175657374120c0a046e616d65180120" .
            "012809221d0a0a48656c6c6f5265706c79120f0a076d6573736167651801" .
            "2001280922270a074d795265706c79120f0a076d65737361676518012001" .
            "2809120b0a0361676518142001280532c8010a0747726565746572123e0a" .
            "0853617948656c6c6f12182e68656c6c6f776f726c642e48656c6c6f5265" .
            "71756573741a162e68656c6c6f776f726c642e48656c6c6f5265706c7922" .
            "0012430a0d53617948656c6c6f416761696e12182e68656c6c6f776f726c" .
            "642e48656c6c6f526571756573741a162e68656c6c6f776f726c642e4865" .
            "6c6c6f5265706c79220012380a054d7953617912182e68656c6c6f776f72" .
            "6c642e48656c6c6f526571756573741a132e68656c6c6f776f726c642e4d" .
            "795265706c79220042300a1b696f2e677270632e6578616d706c65732e68" .
            "656c6c6f776f726c64420f48656c6c6f576f726c6450726f746f50016206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

