<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helloworld.proto

namespace Helloworld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>helloworld.MyReply</code>
 */
class MyReply extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>string message = 1;</code>
     */
    private $message = '';
    /**
     * <code>int32 age = 20;</code>
     */
    private $age = 0;

    public function __construct() {
        \GPBMetadata\Helloworld::initOnce();
        parent::__construct();
    }

    /**
     * <code>string message = 1;</code>
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * <code>string message = 1;</code>
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;
    }

    /**
     * <code>int32 age = 20;</code>
     */
    public function getAge()
    {
        return $this->age;
    }

    /**
     * <code>int32 age = 20;</code>
     */
    public function setAge($var)
    {
        GPBUtil::checkInt32($var);
        $this->age = $var;
    }

}

