<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: my.proto

namespace GPBMetadata;

class My
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0010a086d792e70726f746f12026d7922170a0a54657374537472696e" .
            "6712090a017318022001280922140a0754657374496e7412090a01731801" .
            "2001280522150a085465737453496e7412090a017318012001281122180a" .
            "0b546573744669786564333212090a017318012001280722480a04546573" .
            "74120d0a056c6162656c180120012809120c0a0474797065180220012805" .
            "120c0a047265707318032003280312150a0d72657175697265644669656c" .
            "64180520012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

